# --- Dual Ensembled QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50000

runner: "episode"

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200  # hard: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "demix_learner"
double_q: True
mixer: "eqmix"
mixing_embed_dim: 32
hypernet_layers: 2
hypernet_embed: 64

agent: 'ernn'

# redq hyper-parameters
mixer_N: 3
mixer_M: 2
agent_N: 1
agent_M: 1

# MC return regularizer
v_reg: False
red_lambda: 0.0

hyper_alpha: 0.002

name: "demix_N3M2n1m1_hyperall0.002_5m_vs_6m"
